version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: improvscoreboard-server
    restart: always
    ports:
      - "3001:3001"

    environment:
      - NODE_ENV=development
      - PORT=3001
      - SQLITE_DB_PATH=/app/data/improvscoreboard.sqlite
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./server:/app
      - /app/node_modules
      - sqlite_data:/app/data
    networks:
      - app-network
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: improvscoreboard-client
    restart: always
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data:
    driver: local