version: '3.8'

services:
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: improvscoreboard-server
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/improvscoreboard?authSource=admin
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - CORS_ORIGIN=http://107.173.85.175:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: improvscoreboard-client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://107.173.85.175:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
